library(dplyr)
file <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors=FALSE)
file$Date<-as.Date(file$Date,"%d/%m/%Y")
csv<-filter(file,file$Date >= as.Date("01/02/2007","%d/%m/%Y") & file$Date <= as.Date("02/02/2007","%d/%m/%Y"))
csv$Global_active_power <- as.numeric(csv$Global_active_power)
globalActivePower <- as.numeric(csv$Global_active_power)
png("plot1.png", width=480, height=480)
hist(csv$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
