library(dplyr)
file <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors=FALSE)
file$Date<-as.Date(file$Date,"%d/%m/%Y")
csv<-filter(file,file$Date >= as.Date("01/02/2007","%d/%m/%Y") & file$Date <= as.Date("02/02/2007","%d/%m/%Y"))
datetime <- strptime(paste(csv$Date, csv$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
csv$Global_active_power <- as.numeric(csv$Global_active_power)
png("plot2.png", width=480, height=480)
plot(datetime, csv$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
