library(dplyr)
file <- read.csv("household_power_consumption.txt", sep = ";", stringsAsFactors=FALSE)
file$Date<-as.Date(file$Date,"%d/%m/%Y")
csv<-filter(file,file$Date >= as.Date("01/02/2007","%d/%m/%Y") & file$Date <= as.Date("02/02/2007","%d/%m/%Y"))
datetime <- strptime(paste(csv$Date, csv$Time, sep=" "), "%Y-%m-%d %H:%M:%S") 
csv$Sub_metering_1 <- as.numeric(csv$Sub_metering_1)
csv$Sub_metering_2 <- as.numeric(csv$Sub_metering_2)
csv$Sub_metering_3 <- as.numeric(csv$Sub_metering_3)

png("plot3.png", width=480, height=480)
plot(datetime, csv$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, csv$Sub_metering_2, type="l", col="red")
lines(datetime, csv$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
